name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  open-pr:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: write file
        run: |
          touch img.png
          touch bad.wtf
          mkdir -p dir/__Snapshot__/dir/
          touch    dir/__Snapshot__/dir/long_path.jpg
      - name: Create Pull Request
        uses: tutu-ru-mobile/create-pull-request@tutu
        with:
          add-pattern-array: |
            **__Snapshot__**
          token: ${{ secrets.GITHUB_TOKEN }}




